ci:
  variables:
    TASK_API_PORT: 8086
    DB_URL: jdbc:mysql://localhost:3306/todolistMicroServices
    DB_USERNAME: root
    DB_PASSWORD: 123456789
  trigger:
    include:
      - project: 'todolist-micro-services/pipeline'
        ref: 'master'
        file: 'src/gradle.yml'
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "main"
